#!/bin/bash 
scriptdir=~/.bsrun
	case $1 in
		-r) exec bash $scriptdir/$2 ;;
		-l) exec ls $scriptdir/ ;;
		-o) exec bash $2 ;;
		-h)	echo "-r [script name] : runscript from file name."
			echo "-l : list all script from the dicrtory. (deflaut dir is ~/.script-runner.)"
			echo "-o [full path of scritp] : run script from a diffrent directory"
			echo "-h : list shows this message." ;;
	esac
